### PR TITLE
Update to JLab 1

### PR DESCRIPTION
**Pull request by jtpio**
Update all the examples so they are compatible with JupyterLab 1.0:

This is mostly focusing on getting them to compile for JupyterLab 1, but they would require another pass to check they are working properly.

### TODO

- [x] 1_hello_world
- [x] 2_commands_and_menus
- [x] 3a_widgets
- [x] 3b_datagrid
- [x] 4a_kernel_output
- [x] 4b_jupyterwidgets
- [x] 5_signals_and_buttons
- [x] 6_kernel_messaging
- [ ] 7_serving_files?

### CODE REVIEW

**Comment by echarles** [comment]
Tried this PR linking examples 1 to 5. jlab can be built with latest jlab.

Only example 1 is an extension (which works as the expected message can be seen in the console`the JupyterLab main application:...)

@jtpio do you get the same behavior?

```
JupyterLab v2.0.0a1
Known labextensions:
   app dir: /opt/datalayer/opt/miniconda3/envs/datalayer/share/jupyter/lab
        1_hello_world v0.1.0  enabled  OK*

   local extensions:
        1_hello_world: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/1_hello_world
        @datalayer/jupyterlab-twitter: /Users/echar4/datalayer/src/jupyterlab/twitter

   linked packages:
        2_commands_and_menus: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/2_commands_and_menus
        3a_widgets: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/3a_widgets
        3b_datagrid: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/3b_datagrid
        4a_kernel_output: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/4a_kernel_output
        4b_jupyterwidgets: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/4b_jupyterwidgets
        5_signals_and_buttons: /Users/echar4/datalayer/repos/jupyterlab-extension-examples/5_signals_and_buttons
```

**Comment by echarles** [comment]
Versions in root README.md should also be updated.

**Comment by jtpio** [comment]
For now I've been installing the extensions one by one with `jupyter labextension install <folder> --debug`, and this is what I have:

```
$ jupyter labextension list
JupyterLab v1.2.1
Known labextensions:
   app dir: /home/jtp/miniconda/envs/jupyterlab-extension-tutorial/share/jupyter/lab
        1_hello_world v0.1.0  enabled  OK*
        2_commands_and_menus v0.1.0  enabled  OK*
        3a_widgets v0.1.0  enabled  OK*
        3b_datagrid v0.1.0  enabled  OK*
        4a_kernel_output v0.1.0  enabled  OK*
        4b_jupyterwidgets v0.1.0  enabled  OK*
        5_signals_and_buttons v0.1.0  enabled  OK*
        6_kernel_messaging v0.1.0  enabled  OK*

   local extensions:
        1_hello_world: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/1_hello_world
        2_commands_and_menus: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/2_commands_and_menus
        3a_widgets: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/3a_widgets
        3b_datagrid: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/3b_datagrid
        4a_kernel_output: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/4a_kernel_output
        4b_jupyterwidgets: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/4b_jupyterwidgets
        5_signals_and_buttons: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/5_signals_and_buttons
        6_kernel_messaging: /home/jtp/git/jtpio/jupyterlab-extension-tutorial/6_kernel_messaging

```

**Comment by echarles** [comment]
so far so good. I checked the log and it returned `a linked package because it does not have extension metadata:   Missing extension module "lib/index.js"`

Indeed I have not built the folder example 2 to 5. When I build, I have them listed. Tested extension 2 and it works fine.

LGTM

**Pull request merged**
